FROM node:22-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

RUN mkdir -p src/utils/logger/logs_registers

EXPOSE 3000

CMD ["npm", "run", "dev"]